Prawn::Fonts::AFM.hide_m17n_warning = true

module Pdf
  class BasePdf
    GREEN = "1A7A50"
    DARK = "1C1C19"
    MUTED = "6B7280"
    LIGHT_BG = "F9FAFB"
    HEADER_BG = "F0F7F4"
    BORDER = "E5E7EB"

    private

    def setup_document(orientation: :portrait)
      Prawn::Document.new(
        page_size: "LETTER",
        margin: [50, 50, 60, 50],
        page_layout: orientation
      )
    end

    def render_header(pdf, title, subtitle: nil, business_name: nil)
      # Green accent line at top
      pdf.save_graphics_state
      pdf.canvas do
        pdf.fill_color GREEN
        pdf.fill_rectangle [0, pdf.bounds.top], pdf.bounds.width + 100, 4
      end
      pdf.restore_graphics_state
      pdf.fill_color "000000"

      pdf.move_down 10

      # Business name
      name = business_name.presence || "My Lending Business"
      pdf.font_size(18) { pdf.text name, style: :bold, color: DARK }
      pdf.move_down 4

      # Title
      pdf.font_size(12) { pdf.text title, color: MUTED }

      # Optional subtitle
      if subtitle.present?
        pdf.move_down 2
        pdf.font_size(9) { pdf.text subtitle, color: MUTED }
      end

      pdf.move_down 6
      pdf.stroke_color BORDER
      pdf.line_width 0.5
      pdf.stroke_horizontal_rule
      pdf.move_down 16
    end

    def render_footer(pdf, note: nil)
      pdf.repeat(:all) do
        pdf.bounding_box([0, 30], width: pdf.bounds.width, height: 20) do
          pdf.font_size(7) do
            disclaimer = note || "Generated by LendSolo"
            pdf.text "#{disclaimer} · #{Date.current.strftime('%B %d, %Y')}", color: "9CA3AF", align: :left
            pdf.text_box "Page #{pdf.page_number}",
              at: [pdf.bounds.width - 60, pdf.bounds.top],
              width: 60, align: :right, size: 7, color: "9CA3AF"
          end
        end
      end
    end

    def section_heading(pdf, text)
      pdf.font_size(13) { pdf.text text, style: :bold, color: GREEN }
      pdf.move_down 10
    end

    def styled_table(pdf, header, rows, opts = {})
      width = opts[:width] || pdf.bounds.width
      cell_size = opts[:cell_size] || 8
      right_align_from = opts[:right_align_from] || 2

      pdf.table([header] + rows, width: width, cell_style: { size: cell_size, padding: [5, 6] }) do |t|
        t.row(0).font_style = :bold
        t.row(0).background_color = HEADER_BG
        t.row(0).text_color = GREEN
        t.row(-1).background_color = LIGHT_BG if opts[:highlight_last]
        t.columns(right_align_from..header.length).align = :right if right_align_from
        t.cells.border_width = 0.5
        t.cells.border_color = BORDER

        yield t if block_given?
      end
    end

    def fmt(num)
      "$#{num.round(2).to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse}"
    end

    def info_box(pdf, pairs)
      # Renders a bordered box with label: value pairs in a 2-column layout
      box_height = ((pairs.length / 2.0).ceil * 22) + 20

      pdf.bounding_box([0, pdf.cursor], width: pdf.bounds.width) do
        pdf.stroke_color BORDER
        pdf.fill_color LIGHT_BG
        pdf.fill_and_stroke_rounded_rectangle [0, pdf.cursor], pdf.bounds.width, box_height, 4
        pdf.fill_color "000000"
        pdf.stroke_color "000000"

        pdf.move_down 12
        pdf.indent(16) do
          pairs.each_slice(2).each do |pair|
            col_width = (pdf.bounds.width - 32) / 2

            pair.each_with_index do |(label, value), i|
              x_offset = i * col_width
              pdf.text_box label, at: [x_offset, pdf.cursor], width: col_width, size: 8, color: MUTED
              pdf.text_box value.to_s, at: [x_offset, pdf.cursor - 10], width: col_width, size: 10, style: :bold, color: DARK
            end
            pdf.move_down 22
          end
        end
      end

      pdf.move_down box_height + 8
    end
  end
end
