module Pdf
  class Form1098Pdf < BasePdf
    FORM_BORDER = "000000"
    FORM_BG = "FFFFFF"
    LIGHT_GRAY = "F5F5F5"
    BOX_LABEL_SIZE = 6.5
    BOX_VALUE_SIZE = 10
    VOID_COLOR = "CCCCCC"

    def initialize(borrower:, lender:, year:)
      @borrower = borrower
      @lender = lender
      @year = year
    end

    def generate
      calculate_data
      # Generate Copy B (for borrower) — this is the primary copy
      render_form(copy: "B")
    end

    def generate_copy_a
      calculate_data
      render_form(copy: "A")
    end

    private

    def calculate_data
      year_start = Date.new(@year, 1, 1)
      year_end = Date.new(@year, 12, 31)

      loans = @borrower.loans.where(user_id: @lender.id).includes(:payments)

      @total_interest = 0.0
      @outstanding_principal = 0.0
      @earliest_origination = nil
      @collateral_addresses = []

      loans.each do |loan|
        year_payments = loan.payments.where(date: year_start..year_end)
        @total_interest += year_payments.sum(:interest_portion).to_f

        # Outstanding principal as of Dec 31
        total_principal_paid = loan.payments.where("date <= ?", year_end).sum(:principal_portion).to_f
        @outstanding_principal += [loan.principal.to_f - total_principal_paid, 0].max

        # Earliest origination
        if @earliest_origination.nil? || loan.start_date < @earliest_origination
          @earliest_origination = loan.start_date
        end

        # Collateral
        @collateral_addresses << loan.collateral_description if loan.collateral_description.present?
      end

      @property_address = if @collateral_addresses.length == 1
        @collateral_addresses.first
      elsif @collateral_addresses.length > 1
        "Various"
      else
        "N/A"
      end
    end

    def render_form(copy:)
      pdf = setup_document
      pdf.font_size 8

      # ── Top header: form identification ──
      render_form_header(pdf, copy)

      pdf.move_down 8

      # ── Main form body ──
      form_top = pdf.cursor
      form_width = pdf.bounds.width
      left_col_width = form_width * 0.5
      right_col_width = form_width * 0.5

      # Draw the outer border
      form_height = 420
      pdf.stroke_color FORM_BORDER
      pdf.line_width 1.5
      pdf.stroke_rectangle [0, form_top], form_width, form_height

      # ── Left column: Filer & Borrower info ──
      render_filer_section(pdf, form_top, left_col_width)
      render_borrower_section(pdf, form_top, left_col_width)

      # ── Right column: Boxes 1-7 ──
      render_amount_boxes(pdf, form_top, left_col_width, right_col_width)

      # ── Property address section (full width, below main boxes) ──
      property_y = form_top - 320
      pdf.line_width 0.5
      pdf.stroke_color FORM_BORDER
      pdf.stroke_line [0, property_y], [form_width, property_y]

      pdf.bounding_box([8, property_y - 4], width: form_width - 16, height: 40) do
        pdf.font_size(BOX_LABEL_SIZE) { pdf.text "Box 7 — Address or description of property securing mortgage", color: MUTED }
        pdf.move_down 3
        pdf.font_size(9) { pdf.text @property_address.to_s.truncate(120), style: :bold, color: DARK }
      end

      # ── Account number line ──
      acct_y = form_top - 360
      pdf.stroke_line [0, acct_y], [form_width, acct_y]
      pdf.bounding_box([8, acct_y - 4], width: form_width - 16, height: 30) do
        pdf.font_size(BOX_LABEL_SIZE) { pdf.text "Account number (see instructions)", color: MUTED }
        pdf.move_down 3
        pdf.font_size(9) { pdf.text "Borrower ID: #{@borrower.id}", color: DARK }
      end

      # ── Footer disclaimer ──
      footer_y = form_top - form_height - 12
      pdf.bounding_box([0, footer_y], width: form_width, height: 40) do
        pdf.font_size(7) do
          copy_label = copy == "A" ? "Copy A — For Internal Revenue Service Center" : "Copy B — For Payer/Borrower"
          pdf.text copy_label, style: :bold, color: DARK
          pdf.move_down 4
          pdf.text "This is important tax information and is being furnished to the IRS. If you are required to file a return, " \
                   "a negligence penalty or other sanction may be imposed on you if this income is taxable and the IRS determines " \
                   "that it has not been reported.", color: MUTED
        end
      end

      # ── LendSolo branded footer ──
      render_footer(pdf, note: "Generated by LendSolo · Form 1098 · Tax Year #{@year}")

      pdf
    end

    def render_form_header(pdf, copy)
      # Green accent line (LendSolo brand)
      pdf.save_graphics_state
      pdf.canvas do
        pdf.fill_color GREEN
        pdf.fill_rectangle [0, pdf.bounds.top], pdf.bounds.width + 100, 4
      end
      pdf.restore_graphics_state
      pdf.fill_color "000000"

      pdf.move_down 10

      # Form title row
      pdf.font_size(7) { pdf.text "Form 1098", style: :bold, color: DARK }
      pdf.font_size(6) { pdf.text "(Rev. January #{@year})", color: MUTED }
      pdf.move_down 2

      copy_label = copy == "A" ? "Copy A — For Internal Revenue Service Center" : "Copy B — For Payer/Borrower"
      pdf.font_size(6) { pdf.text "Department of the Treasury — Internal Revenue Service", color: MUTED }

      pdf.move_down 4
      pdf.font_size(14) { pdf.text "Mortgage Interest Statement", style: :bold, color: DARK }
      pdf.font_size(8) { pdf.text "OMB No. 1545-0901    #{copy_label}    Tax Year #{@year}", color: MUTED }

      pdf.move_down 4
      pdf.stroke_color GREEN
      pdf.line_width 1.5
      pdf.stroke_horizontal_rule
      pdf.stroke_color "000000"
      pdf.line_width 0.5
    end

    def render_filer_section(pdf, form_top, col_width)
      section_height = 160

      # Vertical divider between columns
      pdf.stroke_color FORM_BORDER
      pdf.line_width 0.5
      pdf.stroke_line [col_width, form_top], [col_width, form_top - 320]

      # Horizontal divider between filer and borrower
      pdf.stroke_line [0, form_top - section_height], [col_width, form_top - section_height]

      pdf.bounding_box([8, form_top - 6], width: col_width - 16, height: section_height - 12) do
        pdf.font_size(BOX_LABEL_SIZE) do
          pdf.text "FILER'S name, street address, city or town, state or province, country, ZIP or foreign postal code, and telephone no.", color: MUTED
        end
        pdf.move_down 6

        lender_name = @lender.business_name.presence || "—"
        pdf.font_size(10) { pdf.text lender_name, style: :bold, color: DARK }
        pdf.move_down 3

        pdf.font_size(8) do
          pdf.text @lender.lender_street_address.to_s, color: DARK if @lender.lender_street_address.present?
          city_state_zip = [@lender.lender_city, @lender.lender_state].select(&:present?).join(", ")
          city_state_zip += " #{@lender.lender_zip}" if @lender.lender_zip.present?
          pdf.text city_state_zip, color: DARK if city_state_zip.present?
        end

        pdf.move_down 8
        pdf.font_size(BOX_LABEL_SIZE) { pdf.text "FILER'S TIN", color: MUTED }
        pdf.move_down 2
        # Show masked TIN on Copy B, full on Copy A (IRS)
        tin_display = @lender.lender_tin.present? ? @lender.lender_tin_masked : "—"
        pdf.font_size(9) { pdf.text tin_display, style: :bold, color: DARK }
      end
    end

    def render_borrower_section(pdf, form_top, col_width)
      borrower_top = form_top - 160
      section_height = 160

      pdf.bounding_box([8, borrower_top - 6], width: col_width - 16, height: section_height - 12) do
        pdf.font_size(BOX_LABEL_SIZE) do
          pdf.text "PAYER'S/BORROWER'S name, street address, city or town, state or province, country, and ZIP or foreign postal code", color: MUTED
        end
        pdf.move_down 6

        pdf.font_size(10) { pdf.text @borrower.name, style: :bold, color: DARK }
        pdf.move_down 3

        pdf.font_size(8) do
          pdf.text @borrower.address_line1.to_s, color: DARK if @borrower.address_line1.present?
          pdf.text @borrower.address_line2.to_s, color: DARK if @borrower.address_line2.present?
          city_state_zip = [@borrower.city, @borrower.state].select(&:present?).join(", ")
          city_state_zip += " #{@borrower.zip}" if @borrower.zip.present?
          pdf.text city_state_zip, color: DARK if city_state_zip.present?
        end

        pdf.move_down 8
        pdf.font_size(BOX_LABEL_SIZE) { pdf.text "PAYER'S/BORROWER'S TIN", color: MUTED }
        pdf.move_down 2
        tin_display = @borrower.tin.present? ? @borrower.tin_masked : "—"
        pdf.font_size(9) { pdf.text tin_display, style: :bold, color: DARK }
      end
    end

    def render_amount_boxes(pdf, form_top, x_offset, col_width)
      box_height = 53
      box_padding = 6
      boxes = [
        { number: "1", label: "Mortgage interest received from\npayer(s)/borrower(s)", value: fmt(@total_interest) },
        { number: "2", label: "Outstanding mortgage principal\nas of 12/31/#{@year}", value: fmt(@outstanding_principal) },
        { number: "3", label: "Mortgage origination date", value: @earliest_origination&.strftime("%m/%d/%Y") || "—" },
        { number: "4", label: "Refund of overpaid interest", value: fmt(0) },
        { number: "5", label: "Mortgage insurance premiums", value: fmt(0) },
        { number: "6", label: "Points paid on purchase of\nprincipal residence", value: fmt(0) },
      ]

      boxes.each_with_index do |box, i|
        y = form_top - (i * box_height)

        # Box border
        pdf.stroke_color FORM_BORDER
        pdf.line_width 0.5
        pdf.stroke_rectangle [x_offset, y], col_width, box_height

        # Alternate background
        if i.even?
          pdf.save_graphics_state
          pdf.fill_color LIGHT_GRAY
          pdf.fill_rectangle [x_offset + 0.5, y - 0.5], col_width - 1, box_height - 1
          pdf.fill_color "000000"
          pdf.restore_graphics_state
        end

        pdf.bounding_box([x_offset + box_padding, y - 4], width: col_width - (box_padding * 2), height: box_height - 8) do
          pdf.font_size(BOX_LABEL_SIZE) do
            pdf.text "#{box[:number]}  #{box[:label]}", color: MUTED
          end
          pdf.move_down 4
          pdf.font_size(BOX_VALUE_SIZE) do
            pdf.text box[:value], style: :bold, color: DARK
          end
        end
      end
    end
  end
end
